const keywordsForGeneralIntention = [
  // Existing general intention keywords
  'can you answer my question',
  'help me with something',
  'I have a query',
  'general question',
  'need assistance',
  'can you help me',
  'hi',
  'hi how are you',
  'hello',
  'yeah',
  'yes',
  'no',
  'maybe',
  'I think so',
  'I don’t think so',
  'sure',
  'of course',
  'right',
  'exactly',
  'I see',
  'um',
  'uh',
  'you know',
  'like',
  'okay',
  'OK',
  'alright',
  'got it',
  'absolutely',
  'definitely',
  'sounds good',
  'fair enough',
  'understood',
  'gotcha',
  'mhm',
  'alrighty',
  'no problem',
  'certainly',
  'indeed',
  'got it',
  'roger that',
  'affirmative',
  'hello there',
  'good morning',
  'good afternoon',
  'good evening',
  'hey',
  'hey there',
  'greetings',
  'how are you',
  'what’s up',
  'is this the portfolio owner',
  'are you the owner',
  'can I talk to the owner',
  'is this the right place',
  'who are you',
  'what is this site about',
  'can I know more about you',
  'can you introduce yourself',
  'tell me about your work',
  'show me your projects',
  'tell me about your portfolio',
  'what do you do',
  'can I ask something',
  'can we talk',
  'do you have a minute',
  'are you available',
  'can you chat with me',
  'I need some details',
  'I need information',
  'I want to know more',
  'I’m curious about your work',
  'is this a chatbot',
  'are you a bot',
];

export default keywordsForGeneralIntention;
