const keywordsForServices = [
  'what services do you provide',
  'what can you do for me',
  'how can you help',
  'what do you offer',
  'can you help with development',
  'services you provide',
  'do you do DevOps',
  'can you build websites',
  'can you build web applications',
  'do you offer AI services',
  'can you integrate AI into my system',
  'do you provide AI development',
  'can you help with AI automation',
  'what kind of automation services do you offer',
  'do you do machine learning development',
  'can you help with system automation',
  'do you build custom web solutions',
  'can you create e-commerce websites',
  'can you develop mobile applications',
  'can you assist with cloud computing services',
  'do you offer cloud infrastructure setup',
  'can you help with API integration',
  'do you provide chatbot development',
  'can you help with automation using AI',
  'can you help with data analysis and AI',
  'can you set up DevOps pipelines',
  'do you provide web scraping services',
  'do you work with IoT integrations',
  'can you build AI-driven websites',
  'do you offer natural language processing (NLP) services',
  'can you help with data-driven decision-making solutions',
  'can you assist with business automation',
  'do you create AI models for businesses',
  'can you provide custom AI tools for my business',
  'can you assist with cloud-native applications',
  'do you develop custom AI solutions for enterprise needs',
  'do you help with AI-powered system optimizations',
  'can you help with robotic process automation (RPA)',
  'can you help with website SEO optimization',
  'do you provide performance tuning for websites',
  'can you build websites with integrated AI tools',
  'do you help with website user experience (UX) design',
  'can you help with website accessibility enhancements',
  'do you provide continuous integration and continuous delivery (CI/CD)',
  'can you help with website speed optimization',
  'can you assist with server and database performance tuning',
  'do you help with building scalable applications',
  'can you integrate machine learning models into my app',
  'do you offer cloud-native app development',
  'can you help with AI-driven data analytics',
  'do you create automated data pipelines',
  'can you provide serverless computing solutions',
  'can you help with web security implementation',
  'do you provide consulting for AI integrations',
  'do you offer cloud data storage solutions',
  'can you help with cross-platform mobile apps',
  'can you provide custom web scraping solutions',
  'do you offer consulting for machine learning strategies',
  'can you optimize existing applications with AI',
  'do you provide help with predictive analytics',
  'can you build data visualizations with AI insights',
  'do you help with integrating AI into IoT systems',
  'can you develop intelligent web applications',
  'do you offer cloud-based business automation',
  'can you help with custom AI-powered recommendation systems',
  'do you provide AI-driven customer support solutions',
  'can you help with developing voice-enabled applications',
  'do you offer multi-cloud infrastructure solutions',
  'can you help with deploying AI applications on the cloud',
  'do you assist with AI and machine learning model deployment',
  'can you help with scaling AI solutions',
  'do you provide consultation for cloud infrastructure management',
  'can you integrate APIs into existing systems',
  'do you offer AI-based fraud detection solutions',
  'can you help with AI model training and tuning',
  'do you provide machine learning model optimization',
  'can you help integrate voice assistants into websites or apps',
  'do you offer AI-based image recognition services',
  'can you develop AI-based predictive maintenance solutions',
];

export default keywordsForServices;
