const keywordsForContact = [
  'how can I contact you',
  'where can I find your email',
  'what is your email address',
  'can I get in touch with you',
  'how do I reach you',
  'contact information',
  'how to connect with you',
  'send you a message',
  'how to reach out to you',
  'can I call you',
  'is there a contact form',
  'can I get your phone number',
  'are you available on social media',
  'can we schedule a meeting',
  'do you have a LinkedIn profile',
  'how can I follow up with you',
  'is there a way to contact you directly',
  'do you have a business card',
  'can I drop you a message somewhere',
  'where can I send an inquiry',
  'can I DM you',
  'how do I communicate with you',
  'where to send a collaboration request',
  'do you have an office address',
  'how do I ask you a question directly',
  'can I set up a consultation with you',
  'do you respond to emails quickly',
  'are you open to direct messages',
  'how can I find your WhatsApp or Telegram',
  'is there a specific way to contact you',
  'what’s the best way to reach you',
  'do you have a contact page',
];

export default keywordsForContact;
