const keywordsForSkills = [
  'what skills do you have',
  'what technologies do you know',
  'what languages do you code in',
  'tell me about your technical skills',
  'what is your expertise',
  'tech stack',
  'are you good at coding',
  'what frameworks do you use',
  'what tools are you proficient in',
  'can you work with modern technologies',
  'do you specialize in front-end, back-end, or full-stack development',
  'what programming paradigms are you familiar with',
  'what kind of coding projects have you done',
  'are you experienced with databases',
  'do you have cloud computing experience',
  'are you skilled in DevOps',
  'can you handle debugging and optimization',
  'how do you keep your skills up-to-date',
  'do you know any design patterns',
  'are you familiar with agile or other development methodologies',
  'can you build scalable applications',
  'do you have experience with APIs',
  'what libraries do you commonly use',
  'how do you approach learning new technologies',
  'are you proficient with version control systems',
  'can you work with CI/CD pipelines',
  'do you have skills in testing frameworks',
  'what development environments or IDEs do you prefer',
  'how versatile is your tech stack',
  'do you have any certifications or training in specific technologies',
  'can you adapt to different technology stacks quickly',
  'what unique technical skills set you apart',
  'are you comfortable working with microservices architecture',
  'do you have experience with machine learning or AI technologies',
  'how well do you know system design and architecture',
  'what skills make you suitable for modern development challenges',
  'are you good at troubleshooting complex systems',
  'do you know any low-code or no-code platforms',
  'how well do you understand data structures and algorithms',
  'what skills do you have that are in demand today',
];

export default keywordsForSkills;
