const keywordsForProjects = [
  'show me your projects',
  'what projects have you worked on',
  'tell me about your projects',
  'do you have a portfolio',
  'can I see your projects',
  'examples of your projects',
  'what have you built',
  'past projects',
  'can you share your recent projects',
  'have you worked on any open-source projects',
  'what kind of projects have you completed',
  'can you provide links to your projects',
  'can you describe the most challenging project you have worked on',
  'what are your favorite projects you have worked on',
  'what technologies did you use in your projects',
  'what kind of clients or industries were your projects for',
  'have you collaborated on any team projects',
  'what personal projects are you proud of',
  'do you have live demos of your projects',
  'can I see your GitHub or other project repositories',
  'what impact have your projects had',
  'have you worked on any freelance or contract projects',
  'are your projects live or in production',
  'can you explain a specific project in detail',
  'what projects demonstrate your full-stack skills',
  'do you have experience with end-to-end project delivery',
  'how do you approach solving problems in your projects',
  'what lessons have you learned from your projects',
  'have you worked on any innovative or unique projects',
  'how do you choose which projects to work on',
  'what is your role in the projects you work on',
  'What is your Personal Portfolio Website?',
  'Can I see your portfolio website?',
  'What technologies are used in your Personal Portfolio Website?',
  'How is your portfolio website responsive?',
  'Can I view your work on GitHub Pages?',
  'What challenges did you face building your portfolio?',
  'Does the portfolio highlight your key projects?',
  'How does this project enhance your personal branding?',
  'Why did you use React and TypeScript for your portfolio?',
  'How is the portfolio optimized for performance and accessibility?',
  'Is your portfolio interactive or static?',
  'How did you host your Personal Portfolio Website?',
  'Does it include animations or transitions?',
  'Can I see the source code for your portfolio?',
  'What is the File Management System project?',
  'How does the system handle files?',
  'Can I see a demo or walkthrough of the File Management System?',
  'What is the summarization feature in this project?',
  'How does the system use FastAPI and React?',
  'How is MongoDB used in the File Management System?',
  'What inspired this project?',
  'How does this system enhance document handling?',
  'Is the File Management System scalable?',
  'What challenges did you face in building this project?',
  'Can this system handle large file uploads?',
  'What text extraction methods are implemented?',
  'How secure is the File Management System?',
  'Is the system optimized for performance?',
  'Can users interact with files directly?',
  'What is the MongoDB Setup & API Integration project?',
  'How did you install and configure MongoDB?',
  'What challenges did you face during integration?',
  'How does MongoDB improve app performance?',
  'Can I see the source code for this integration?',
  'How seamless is the frontend-backend communication?',
  'Is MongoDB optimized for specific workloads?',
  'What Linux commands were used for setup?',
  'How is this project beneficial for scalability?',
  'Did you use authentication for MongoDB?',
  'What kind of API endpoints were created?',
  'What technologies were paired with MongoDB?',
  'Can this setup work in a production environment?',
  'What lessons did you learn from this project?',
  'How portable is the integration across platforms?',
];

export default keywordsForProjects;
