const keywordsForExperienceIntent = [
  'what is your experience',
  'how long have you been working',
  'tell me about your experience',
  'what have you done so far',
  'how experienced are you',
  'your professional background',
  'work history',
  'how many years have you been in this field',
  'what industries have you worked in',
  'can you share your professional journey',
  'what roles have you taken on',
  'have you worked on any notable projects',
  'how would you describe your career so far',
  'what is your expertise in the field',
  'what kind of jobs have you done',
  'have you worked in teams or independently',
  'what professional skills have you developed',
  'can you describe your past roles',
  'what experience do you bring to the table',
  'can you share details of your career progression',
  'what companies or clients have you worked with',
  'do you have experience in leadership or management',
  'how has your experience shaped your current skillset',
  'can you summarize your work history',
  'what type of work environments have you been part of',
  'have you ever led a project or a team',
  'what challenges have you faced in your career',
  'can you list the most impactful projects you have worked on',
  'what technologies have you gained experience with',
  'have you worked in agile or DevOps environments',
];

export default keywordsForExperienceIntent;
